name: CI

on:
  push:
    branches: [ test_ci ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      # List the files
      - name: List all files
        run: ls

      # Install Python
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      
      # Create a new file
      - name: Run Python script
        run: python create_file.py

      # List the file again (prove the python worked)
      - name: List all files again
        run: ls

  display:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Print a value
        run: echo "Hello from another Job"
