name: outputs_demo_2

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
        output1: ${{ steps.step1.outputs.data }}
      
    steps:
        - name: Checkout branch
          uses: actions/checkout@v4

        - name: Setup Python
          run: 

 

