name: outputs_demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      
    steps:
      - id: step1
        run: echo "::set-ouput name=test::Hello"
      - id: step2
        run: echo "::set-ouput name=test::world!"

  job2:
    runs-on: ubuntu-latest
    needs: job1
      
    steps:
      - id: step1
        run: echo ${{ needs.job1.outputs.output1 }} ${{ needs.job1.outputs.output2 }}

 
     


