name: outputs_demo_2

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
        output1: ${{ steps.contents.outputs.data }}
      
    steps:
        - name: Checkout branch
          uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10' 

        - name: Run Python script
          id: contents
          run: |
            python create_file.py
            contents=$( cat read_me.txt )
            echo "data=$contents" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - run: echo ${{ needs.job1.outputs.output1 }}

